### ISSUE TITLE
USER STORY: About page

### ISSUE THREAD

**Issue by Anka-S** [Anka-S/hata-na-tata#12]
As a:  **Product Owner**
I want to: **tell the user about the creators of the restaurant**
So that: **user will be engaged to visit the restaurant**

### Acceptance criteria
- [ ] Content field
- [ ] Image of creators

### Tasks
- [ ] Create an app
- [ ] Create HTML page
- [ ] Add the link to the navbar
