### ISSUE TITLE
USER STORY: Leave reviews

### ISSUE THREAD

**Issue by Anka-S** [Anka-S/hata-na-tata#2]
As a:  **user**
I want to: **leave a review**
So that: **I can share my experience with other users**

### Acceptance criteria
- [x] Text field for review
- [x] Rate system?

### Tasks
- [x] Create models for review
- [x]  Add CRUD functionality
- [x]  Connect models with views
