### ISSUE TITLE
USER STORY: Update Menu

### ISSUE THREAD

**Issue by Anka-S** [Anka-S/hata-na-tata#8]
As an:  **admin**
I want to: **add/update the information  on the Menu page**
So that: **user can choose from the valid dishes**

### Acceptance criteria
- [x] Only the admin can add /update information
- [x] Readable content
- [x] Title

### Tasks
- [x] Create models for menu section and menu items
- [x] Connect models with view
